[pytest]
testpaths = tests
pythonpath = .
norecursedirs =
    .build_venv
    .git
    .pytest_cache
    __pycache__
    build
    dist
    releases
    store_package
    tesseract_portable
    tessdata
    _alt
    _WARTUNG
