[pytest]
pythonpath = .
testpaths = tests
addopts = -p no:flask --basetemp=.pytest_temp
norecursedirs =
    .build_venv
    .git
    .pytest_cache
    .pytest_temp
    .pytest_tmp*
    .hypothesis
    .turbo
    .nyc_output
    .tox
    __pycache__
    build
    dist
    releases
    store_package
    tesseract_portable
    tessdata
    _alt
    _WARTUNG
